- name: Skip if migration already completed
  ansible.builtin.meta: end_play
  when: lookup('ansible.builtin.file', version_file) is version(migration_version, '>=')

- name: Remove call to pull-based upgrade-mosaic playbook
  ansible.builtin.copy:
    src: files/update-mosaic.sh
    dest: /opt/mosaic/update-mosaic.sh
    mode: "0644"

- name: Remove pull based upgrade-mosaic playbook
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/mosaic/ansible/playbooks/upgrade-mosaic.yml
    - /opt/mosaic/ansible/tasks/upgrade-mosaic-devnet.yml
    - /opt/mosaic/ansible/tasks/upgrade-mosaic-testnet.yml
    - /opt/mosaic/ansible/tasks/upgrade-package.yml

- name: Install latest packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - mosaic-testnet-solo
      - mosaic-chain-devnet
      - mosaic-pro-indexer
      - mosaic-pro-indexer-rc
      - mosaic-announcer
      - mosaic-announcer-rc
      - mosaic-admin-backend
      - mosaic-admin-backend-rc
    state: latest

- name: Read file using shell
  ansible.builtin.command: cat /opt/mosaic/artifacts/active-network.env
  register: active_network_env
  changed_when: false

- name: Set file content as fact
  ansible.builtin.set_fact:
    network: "{{ active_network_env.stdout | trim }}"

- name: Enable and restart mosaic services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop:
    - "mosaic-chain-{{ network }}.service"
    - "mosaic-announcer-{{ network }}.service"
    - "mosaic-indexer-{{ network }}.service"
    - "mosaic-admin-backend-{{ network }}.service"
  register: service_result
  until: service_result is succeeded
  retries: 10
  delay: 10

- name: Set version counter to {{ migration_version }}
  ansible.builtin.copy:
    dest: "{{ version_file }}"
    content: "{{ migration_version }}"
    mode: "0644"
