- name: Skip if migration already completed
  ansible.builtin.meta: end_play
  when: lookup('ansible.builtin.file', version_file) is version(migration_version, '>=')

- name: Specify subnet for allow private IP flag
  ansible.builtin.replace:
    path: "/etc/systemd/system/mosaic-chain-{{ item }}.service"
    regexp: '--allow-private-ip \\'
    replace: '--allow-private-ip 10.137.0.0/16 \\'
  loop:
    - testnet
    - devnet
    - mainnet

- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Set version counter to {{ migration_version }}
  ansible.builtin.copy:
    dest: "{{ version_file }}"
    content: "{{ migration_version }}"
    mode: "0644"
