- name: Upgrade announcer testnet
  ansible.builtin.include_tasks: /opt/mosaic/ansible/tasks/upgrade-package.yml
  vars:
    package_name: mosaic-announcer-rc
    upgrade_fact_name: announcer_upgraded

- name: Restart announcer testnet service if package was upgraded
  ansible.builtin.systemd:
    name: mosaic-announcer-testnet
    state: restarted
  when: announcer_upgraded

- name: Upgrade Admin Backend testnet
  ansible.builtin.include_tasks: /opt/mosaic/ansible/tasks/upgrade-package.yml
  vars:
    package_name: mosaic-admin-backend-rc
    upgrade_fact_name: admin_backend_upgraded

- name: Restart admin backend testnet service if package was upgraded
  ansible.builtin.systemd:
    name: mosaic-admin-backend-testnet
    state: restarted
  when: admin_backend_upgraded

- name: Upgrade Chain Testnet
  ansible.builtin.include_tasks: /opt/mosaic/ansible/tasks/upgrade-package.yml
  vars:
    package_name: mosaic-testnet-solo
    upgrade_fact_name: chain_testnet_upgraded

- name: Stop indexer testnet
  ansible.builtin.systemd:
    name: mosaic-indexer-testnet
    state: stopped
  when: chain_testnet_upgraded

- name: Update testnet solochain chainspec
  ansible.builtin.include_tasks: /opt/mosaic/ansible/tasks/update-chainspec.yml
  vars:
    type: solo
    spec_format: spec-*.json
    latest_file_name: solo-latest.json
    task_network: testnet
  when: chain_testnet_upgraded

- name: Restart chain testnet service if package was upgraded
  ansible.builtin.systemd:
    name: mosaic-chain-testnet
    state: restarted
  when: chain_testnet_upgraded

- name: Upgrade Indexer testnet
  ansible.builtin.include_tasks: /opt/mosaic/ansible/tasks/upgrade-package.yml
  vars:
    package_name: mosaic-pro-indexer-rc
    upgrade_fact_name: indexer_testnet_upgraded

- name: Wait for chain testnet to be started up
  ansible.builtin.include_tasks: /opt/mosaic/ansible/tasks/wait-for-chain-rpc.yml
  when: indexer_testnet_upgraded or chain_testnet_upgraded

- name: Restart indexer testnet service if package was upgraded
  ansible.builtin.systemd:
    name: mosaic-indexer-testnet
    state: restarted
  when: indexer_testnet_upgraded or chain_testnet_upgraded
