- name: Skip if migration already completed
  ansible.builtin.meta: end_play
  when: lookup('ansible.builtin.file', version_file) is version(migration_version, '>=')

- name: Read file using shell
  ansible.builtin.command: cat /opt/mosaic/artifacts/active-network.env
  register: active_network_env
  changed_when: false

- name: Set file content as fact
  ansible.builtin.set_fact:
    network: "{{ active_network_env.stdout | trim }}"

- name: Only proceed for devnet
  ansible.builtin.meta: end_play
  when: network != "devnet"

- name: Upgrade mosaic-chain-node package to ensure new relay chainspec is installed
  ansible.builtin.apt:
    name: mosaic-chain-node
    state: latest
    update_cache: true
  register: apt_result

- name: Stop devnet chain service
  ansible.builtin.systemd_service:
    name: mosaic-chain-devnet.service
    state: stopped

- name: Delete old embedded relay chain database
  ansible.builtin.file:
    path: /var/lib/mosaic-devnet/chains/paseo
    state: absent

- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Start devnet chain service
  ansible.builtin.systemd_service:
    name: mosaic-chain-devnet.service
    enabled: true
    state: started
  register: service_result
  until: service_result is succeeded
  retries: 10
  delay: 10

- name: Set version counter to {{ migration_version }}
  ansible.builtin.copy:
    dest: "{{ version_file }}"
    content: "{{ migration_version }}"
    mode: "0644"
